const QUOTES = [
    'The life of Rama shows the immense Possibility of being Human – the capability to rise above All Challenges.',
    'Devotion is when your involvement with life is so absolute that you yourself do not matter anymore.',
    'Water is life-making material. Saving water resources is Saving Life.',
    'When you were a child, someone had to work hard to make you miserable. Today, someone has to work hard to make you happy. Time to understand that the source of Human experience is within oneself.',
    'The more exclusive you make yourself in thought and emotion, the more excluded from Life you become.',
    'If you want success and joy in whatever you do, the most important thing is Clarity of Perception.',
    'This is the nature of your Mind: if you try to avoid certain thoughts, only those will occur.',
    'When you spend time in the forest, you realize you are just one more Life. It is a huge spiritual step to feel for Life around you the way you feel for yourself.',
    'The Mind, which is the greatest Miracle, has become a misery-manufacturing machine for too many people.',
    'Do not save your Joy for later. When you are joyful, your whole life is a celebration.',
    'Whatever your life situation, there is no reason to be miserable. You came with nothing, so you are always on the profit side.',
    'When it comes to Joy, Love, and the Exuberance of Life, you are the Source of it.',
    'The best way to be receptive to Grace is to become less of yourself.',
    'Once you see the limitations in which you exist, a natural longing to Go Beyond them arises – and that is your biggest fortune.',
    'Those who are absolutely sure of everything have put their Intelligence in cold storage.',
    'Living an Exuberant Life is only possible when you are able to dance upon the uncertainties of life.',
    'What is a friend? A friend is another confused human being like you. If the two of you can be with each other sincerely, that is when real friendship happens.',
    'Relationships are not about compatibility, companionship, or seeking happiness from each other. They are an opportunity to create a Union that paves the way to a greater possibility.',
    'Whether it is song, dance, or work – if you throw yourself into it with total Abandon, your life will become wonderful.',
    'If who you are is clearly established within yourself, what people say will not matter.',
    'Love is the longing to include someone as a part of you – to expand the boundaries of who you are beyond yourself.',
    'If there is love in your heart, no need for kindness. Love guides you through life.',
    'We may not always be able to change the physical situations around us. But no one can stop us from changing the way we Experience them.',
    'Climbing has a cost, but falling is free. You just need to learn to fall into beautiful spaces – and the most beautiful space is Within You.',
    'When you become silent within yourself, you will perceive Life in a way you cannot imagine – in utmost profoundness.',
    'Wherever you are, whatever you are exposed to, pick up the best from every situation. Then, Life is Learning.',
    'Kalabhairava is not only about Death – He is about Time. The quality of your life essentially depends on how you use your Time.',
    'Life is a limited amount of time. You can make it mediocre, terrible, or fantastic. This is all the choice you have.',
    'Do not waste your time and Life on things that do not matter. What truly matters to you, commit to it one hundred percent – today, not tomorrow.',
    'Mastery of anything does not come without absolute Devotion.',
    'Meditation is not a conquest or achievement – it is a homecoming. It is not about going somewhere – it is just falling back into yourself.',
    'What fragrance is to a flower, Love is to a human being.',
    'No matter what you did yesterday, in this moment you can be a wonderful human being if you want to. Existence has given you this Freedom.',
    'Belief means you have made conclusions about things that you have no clue about.',
    'No one can achieve wellbeing through someone else’s suffering. Even if you temporarily benefit, you will pay for it.',
    'You are only given the raw material for your Life. What you make out of it is up to you.',
    'It is not about agreeing with me or disagreeing with me. Just Be with me and Blossom beyond limitations.',
    'A society that does not respect and support its Women cannot progress and prosper. May the Feminine blossom around the world.',
    'Who we are in the world is shaped by the times and situations. Who we are Within should never be shaped by them.',
    'Life is generous to those who know how to receive. Those who know how to make the most of it experience Fulfillment. On this Full Moon of Fulfillment, may you be open to life’s generosity.',
    'How tomorrow happens is decided by how you Think, Feel, and Perceive Life today.',
    'When you are free from anger, resentment, and malice, whatever you touch, you touch Lovingly.',
    'There is always one more step to climb. That is why Life is worth living.',
    'If you maintain Exuberance of energy, freshness of mind, and a loving heart, every day is a new adventure.',
    'There is no cause greater than Life.',
    'To make your surroundings pleasant, you need cooperation. To make your body, mind, and energy pleasant is one hundred percent your business.',
    'If your Intelligence was working for you, you would not make yourself miserable. Within yourself, you would create the Best – outside, you would do your Best.',
    'When you go by your body and intellect alone, life is a circus. When the intelligence of the Divine guides your life, it becomes a dance.',
    'There are two fundamental forces constantly at work within you: self-preservation and the longing to Expand. Once you transcend the instinct of self-preservation, every cell in your body will come to Ease.',
    'Love means being willing to Nurture another Life beyond opinions and prejudice.',
    'Music should be an Exploration, an Enrichment of Life. If it becomes mechanical, machines will take over – they will always do the mechanical better.',
    'In a world where information is available to everyone, Education must become Inspiration, not an accumulation of knowledge.',
    'Whatever you are doing in life, you chose it in some way. Do it as the most important thing – it shall become your Meditation.',
    'Realizing the Full Potential of Life is more important than how long you live.',
    'Taking care of the environment is not an obligation – our environment is our life.',
    'If you are truly Committed to what you care for, the whole world will support you.',
    'No matter your religion, race, or caste – if you are human, Mahashivratri is for you. The science of turning inward is for you, because Human Wellbeing is created from within.',
    'You are not suffering Life. You are suffering your memory and imagination.',
    'Success is when situations do not decide who you are – you decide how the situation should be.',
    'Yoga means Union. Yoga also means ultimate empowerment. If you are in union with everything, it is a tremendous empowerment.',
    'If you are present, I am always present – all your life and beyond. Even after I leave my body, I will still be present.',
    'Breath and heartbeat are vital for the body. Being Meditative is vital for the Human Being.',
    'From today onward, do not drag your feet. Dance your way through Life – whatever you are doing, whatever is happening.',
    'Education needs Inspiration, not just information. Only inspired human beings can transform their own lives and the lives around them.',
    'Life is not in its goal. Life is in its process – in how you Experience it within yourself right now.',
    'Love does not give you sense. It just gives you the right intent.',
    'When new situations arise – even ones you do not like – Embrace them. The less resistance you have, the more agile and effective you become.',
    'It is the Nature of Life to move from one possibility to the next. But it is your psychological framework that chooses the comfort of the familiar over Life.',
    'When you are Joyful, you are not in conflict with anyone, and you do the most wonderful things.',
    'May your dreams not come true, may your hopes not be fulfilled, because they are based on what you know. Explore Possibilities that have never been touched before.',
    'Sankranti is a Celebration of all that makes our Life – the soil, animals, air, water, and people. Rejoice!',
    'Life is not about What you do. It is all about How you do it.',
    'When you become a slave of logic, you are missing the Magic of Life. My work is to take people beyond the framework of logic into the true Magic of our own Existence.',
    'Tomorrow never comes. That is the beauty of life: you only need to learn to handle today. One day at a time, one moment at a time.',
    'How profoundly you are involved – that is how profound the experience of life is.',
    'Yoga is about aligning Oneself with the cosmic geometry. Through this alignment, boundless Energy, Intelligence, and Wellbeing arise.',
    'This is the time when the Sun is at its fullest. Life is at its fullest. If you want your Life to bear fruit, if you want Transformation – this is the Time.',
    'The idea of Sadhana is not to go somewhere. It is to come to a state where you can simply Be here. What is here is everywhere – what is not here is nowhere.',
    'Being with a Guru is not about comfort but a continuous adventure of breaking limitations.',
    'Once your Love, Joy, and Peace depend on someone else, you shall never know these qualities as your own.',
    'Every aspect of Creation – from a grain of sand to a mountain, a drop to an ocean – is a manifestation of an Intelligence far beyond the human intellect.',
    'Whatever situations happen in your life, you can either come out of them with greater strength or be left broken by them. This is a Choice you have.',
    'In Stillness, there is no time.',
    'Whatever you have – your Love, your Joy, your Skills – show them now. Do not try to save them for another lifetime.',
    'You cannot transform the world without transforming the Individual.',
    'It is time to shed the burdens of the past year and come out Fresh and Alive.',
    'If you care for people around you, you must make yourself into a person they enjoy being with.',
    'Karma has nothing to do with good and bad. It is only about cause and effect.',
    'If you pay Attention to the Life that you are, it will blossom within you.',
    'We do not want to Live recycled lives. We want to write our own scripts.',
    'Whether you walk or dance, work or play, cook or sing – do it with total awareness or with total abandon. Either way, you are one with creation.',
    'Believing means assuming something you do not truly know. Seeking means recognizing that you do not know.',
    'Love needs response – otherwise, it will not last long. Devotion does not need anyone’s help – you are simply on by yourself.',
    'The secret of life is to see everything with a Non-Serious eye, but to be Absolutely Involved. Like a sport. Involved, not entangled.',
    'Abundance is not about your clothes, home, or car. True Abundance is about how joyful, loving, and ecstatic you are.',
    'If you have any Love in your heart for your children, the best thing you can do is not to teach them, but to work upon yourself.',
    'Guru’s Grace is not designed to fulfill your plans but Life’s plan for You.',
    'Human intelligence holds the greatest potential in the known universe, if only we use it Consciously.',
    'If you want to know the Joy of activity, the first and foremost thing is to give yourself to activity with total Abandon.',
    'Their own thoughts, emotions, and needs keep most people busy for a lifetime. To be above this is Yoga.',
];

export function getRandomQuote() {
    return QUOTES[Math.floor(Math.random() * QUOTES.length)];
}
